title: ITSC 2025 Workshop on Improving Safety for Motorcycles and Vulnerable Road Users through ITS
# description: Webpage for the ITSC 2025 workshop on Improving Safety for Motorcycles and Vulnerable Road Users through ITS
remote_theme: pages-themes/cayman@v0.2.0
markdown: GFM
plugins:
  - jekyll-remote-theme
